NAME	= {{ name }}
{# TAG		= $(shell git rev-parse --short HEAD) #}
TAG     = {{ tag }}
IMG		= ${NAME}:${TAG}
LATEST	= ${NAME}:latest
ROOT 	= $(shell echo "${PWD}")
SHORT_DESCRIPTION = "PHP Docker Image fully configurable by environment variables."

build: build-image tag-main-version tag-version tag-latest
force-build: force-build-image tag-main-version tag-version tag-latest

build-image:
	@docker build --pull --cache-from "${NAME}" --progress plain -t "${IMG}" .

force-build-image:
	@docker build --no-cache --pull --progress plain -t "${IMG}" .

tag-latest:
	docker tag ${IMG} ${LATEST}

tag-version:
	$(eval $@_PHP_TAG := ${NAME}:$(shell docker run ${IMG} php --version | head -n 1 | cut -d ' ' -f2 | cut -c1-6))
	docker tag "${IMG}" "$($@_PHP_TAG)"

tag-main-version:
	$(eval $@_PHP_TAG := ${NAME}:$(shell docker run ${IMG} php --version | head -n 1 | cut -d ' ' -f2 | cut -c1-3))
	docker tag "${IMG}" "$($@_PHP_TAG)"

test:
	container-structure-test test --image "${IMG}" --config tests/structure-test.yaml

official-test:
	~/official-images/test/run.sh "${IMG}"

dockerhub-description:
	@docker run --volume "${ROOT}:/workspace" \
		--env DOCKERHUB_USERNAME='${DOCKER_USER}' \
		--env DOCKERHUB_PASSWORD='${DOCKER_PASSWORD}' \
		--env DOCKERHUB_REPOSITORY='${NAME}' \
		--env SHORT_DESCRIPTION='${SHORT_DESCRIPTION}' \
		--env README_FILEPATH='/workspace/README.md' \
		peterevans/dockerhub-description:2

push-image:
	@docker push ${NAME}

push: push-image dockerhub-description

login:
	@docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}"
