ARCH := $(shell uname -m | grep -qE 'x86_64|amd64' && echo amd || echo arm)
NAME	= {{ name }}
{# TAG		= $(shell git rev-parse --short HEAD) #}
TAG     = {{ tag }}
IMG		= ${NAME}:${TAG}-${ARCH}
LATEST	= ${NAME}:latest
ROOT 	= $(shell echo "${PWD}")
SHORT_DESCRIPTION = "PHP Docker Image fully configurable by environment variables."

build: build-image tag-main-version tag-version
force-build: force-build-image tag-main-version tag-version
create-manifests: create-version-manifest create-latest-manifest

build-image:
	@docker build --provenance=false --pull --cache-from "${NAME}" --progress plain -t "${IMG}" .

force-build-image:
	@docker build --provenance=false --no-cache --pull --progress plain -t "${IMG}" .

tag-latest:
	docker tag ${IMG} ${LATEST}

tag-version:
	$(eval $@_PHP_TAG := ${NAME}:$(shell docker run ${IMG} php --version | head -n 1 | cut -d ' ' -f2 | cut -c1-6))
	docker tag "${IMG}" "$($@_PHP_TAG)-${ARCH}"

tag-main-version:
	$(eval $@_PHP_TAG := ${NAME}:$(shell docker run ${IMG} php --version | head -n 1 | cut -d ' ' -f2 | cut -c1-3))
	docker tag "${IMG}" "$($@_PHP_TAG)-${ARCH}"

create-version-manifest:
	$(eval $@_PHP_TAG := ${NAME}:$(shell docker run ${IMG} php --version | head -n 1 | cut -d ' ' -f2 | cut -c1-6))

	docker manifest create --amend $($@_PHP_TAG) \
	$($@_PHP_TAG)-arm \
	$($@_PHP_TAG)-amd \

	docker manifest push $($@_PHP_TAG)

create-latest-manifest:
	$(eval $@_PHP_TAG := ${NAME}:$(shell docker run ${IMG} php --version | head -n 1 | cut -d ' ' -f2 | cut -c1-3))

	docker manifest create --amend ${LATEST} \
	$($@_PHP_TAG)-arm \
	$($@_PHP_TAG)-amd \

	docker manifest push ${LATEST}

test:
	container-structure-test test --image "${IMG}" --config tests/structure-test.yaml

official-test:
	~/official-images/test/run.sh "${IMG}"

dockerhub-description:
	@docker run --volume "${ROOT}:/workspace" \
		--env DOCKERHUB_USERNAME='${DOCKER_USER}' \
		--env DOCKERHUB_PASSWORD='${DOCKER_PASSWORD}' \
		--env DOCKERHUB_REPOSITORY='${NAME}' \
		--env SHORT_DESCRIPTION='${SHORT_DESCRIPTION}' \
		--env README_FILEPATH='/workspace/README.md' \
		peterevans/dockerhub-description:2

push-image:
	@docker push --all-tags ${NAME}

push: push-image dockerhub-description

login:
	@docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}"
