schemaVersion: "2.0.0"

globalEnvVars:

metadataTest:
  env:
    - key: PHP_ENABLE_XDEBUG
      value: false
  labels:
    - key: 'maintainer'
      value: 'Tobias Schifftner <ts@ambimax.de>'
  entrypoint: ["/usr/local/bin/entrypoint.sh"]
  cmd: ["bash"]
  workdir: "/var/www/htdocs"

commandTests:
  - name:  "check php version"
    command: "php"
    args: ["--version"]
    expectedOutput:
      - PHP
      - 7.0.
      - cli
      - OPcache

  - name:  "check git"
    command: "git"
    args: ["--version"]
    expectedOutput:
      - git version

  - name:  "check mysql"
    command: "mysql"
    args: ["--version"]
    expectedOutput:
      - mysql

  - name:  "check redis-cli"
    command: "redis-cli"
    args: ["-v"]
    expectedOutput:
      - redis-cli

  - name:  "check composer"
    command: "composer"
    args: ["--version"]
    expectedOutput:
      - Composer version

  - name:  "check n98-magerun"
    command: "n98-magerun"
    args: ["--version"]
    expectedOutput:
      - n98-magerun

  - name:  "check modman"
    command: "modman"
    args: ["--version"]
    expectedOutput:
      - Module Manager version

  - name:  "check zettr"
    command: "zettr"
    args: ["--version"]
    expectedOutput:
      - Zettr version

  - name:  "check php extensions"
    command: "php"
    args: ["-m"]
    expectedOutput:
      - apcu
      - bcmath
      - calendar
      - ctype
      - curl
      - dom
      - exif
      - fileinfo
      - ftp
      - gd
      - gettext
      - hash
      - iconv
      - igbinary
#      - imagick
      - intl
      - json
      - libxml
      - lzf
      - mbstring
      - mcrypt
      - memcached
      - mysqli
      - mysqlnd
      - openssl
      - PDO
      - pdo_mysql
      - pdo_sqlite
      - Phar
      - redis
      - Reflection
      - session
      - SimpleXML
      - soap
      - sockets
      - SPL
      - sqlite3
      - standard
      - tidy
      - tokenizer
      - xml
      - xmlreader
      - xmlrpc
      - xmlwriter
      - xsl
      - Zend OPcache
      - zip
      - zlib

  - name:  "check phpunit 5"
    command: "phpunit5"
    args: ["--version"]
    expectedOutput:
      - 'PHPUnit 5'
      - Sebastian
      - Bergmann

  - name:  "check phpunit 6"
    command: "phpunit6"
    args: ["--version"]
    expectedOutput:
      - 'PHPUnit 6'
      - Sebastian
      - Bergmann

  - name:  "check codeception"
    command: "codecept"
    args: ["--version"]
    expectedOutput:
      - Codeception

  - name:  "check phpmd"
    command: "phpmd"
    args: ["--version"]
    expectedOutput:
      - PHPMD

  - name:  "check phpcs2"
    command: "phpcs2"
    args: ["--version"]
    expectedOutput:
      - 'PHP_CodeSniffer version 2'

  - name:  "check phpcs3"
    command: "phpcs3"
    args: ["--version"]
    expectedOutput:
      - 'PHP_CodeSniffer version 3'

  - name:  "check phpcbf2"
    command: "phpcbf2"
    args: ["--version"]
    expectedOutput:
      - 'PHP_CodeSniffer version 2'

  - name:  "check phpcbf3"
    command: "phpcbf3"
    args: ["--version"]
    expectedOutput:
      - 'PHP_CodeSniffer version 3'


fileExistenceTests:
  - name: 'n98-magerun'
    path: '/tools/n98-magerun'
    shouldExist: true
    isExecutableBy: 'group'

  - name: 'composer'
    path: '/tools/composer'
    shouldExist: true
    isExecutableBy: 'group'

  - name: 'mhsendmail'
    path: '/tools/mhsendmail'
    shouldExist: true
    isExecutableBy: 'group'

  - name: 'modman'
    path: '/tools/modman'
    shouldExist: true
    isExecutableBy: 'group'

  - name: 'zettr'
    path: '/tools/zettr'
    shouldExist: true
    isExecutableBy: 'group'

  - name: 'phpunit5'
    path: '/tools/phpunit5'
    shouldExist: true
    isExecutableBy: 'group'

  - name: 'phpunit6'
    path: '/tools/phpunit6'
    shouldExist: true
    isExecutableBy: 'group'

  - name: 'codecept'
    path: '/tools/codecept'
    shouldExist: true
    isExecutableBy: 'group'

  - name: 'phpmd'
    path: '/tools/phpmd'
    shouldExist: true
    isExecutableBy: 'group'

  - name: 'phpcs2'
    path: '/tools/phpcs2'
    shouldExist: true
    isExecutableBy: 'group'

  - name: 'phpcs3'
    path: '/tools/phpcs2'
    shouldExist: true
    isExecutableBy: 'group'

  - name: 'phpcbf2'
    path: '/tools/phpcbf2'
    shouldExist: true
    isExecutableBy: 'group'

  - name: 'phpcbf3'
    path: '/tools/phpcbf3'
    shouldExist: true
    isExecutableBy: 'group'

  - name: 'xmllint'
    path: '/tools/xmllint'
    shouldExist: true
    isExecutableBy: 'group'

  - name: 'phplint'
    path: '/tools/phplint'
    shouldExist: true
    isExecutableBy: 'group'

  - name: 'codesniffer'
    path: '/tools/codesniffer'
    shouldExist: true
    isExecutableBy: 'group'



fileContentTests:
  - name: 'php.ini'
    path: '/usr/local/etc/php/conf.d/zz-php.ini'
    expectedContents:
      - 'sendmail_path \= "\/tools\/mhsendmail --smtp-addr=\\"mailhog:1025\\""'
