# .prettierrc or .prettierrc.yaml
trailingComma: 'es5'
tabWidth: 4
semi: false
singleQuote: true
printWidth: 120

overrides:
  - files: '*.md.twig'
    options:
      parser: markdown
  - files:
      - '*.yml'
      - '*.yaml'
      - '*.json'
    options:
      tabWidth: 2
