name: Test Suite

on:
  push:
  workflow_dispatch:

jobs:
  build-images:
    timeout-minutes: 20
    strategy:
      matrix:
        WORKDIR:
          - 8.1/alpine3.22
          - 8.2/alpine3.23
          - 8.2/trixie
        os: [ubuntu-latest, self-hosted]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare environment
        run: bash ${GITHUB_WORKSPACE}/.github/scripts/prepare-workflow.sh

      - name: Build image
        working-directory: 'dist/images/${{ matrix.WORKDIR }}'
        run: make build

      - name: Test image
        working-directory: 'dist/images/${{ matrix.WORKDIR }}'
        run: make test

      - name: Additional image tests
        working-directory: 'dist/images/${{ matrix.WORKDIR }}'
        run: make official-test

      - name: Display all docker images
        if: ${{ always() }}
        run: docker images

      - name: Login to Docker Registry
        if: github.ref == 'refs/heads/v2'
        uses: docker/login-action@v1
        with:
          # We push to the default registry currently. If you want to push to a different registry,
          # uncomment the line below.
          # login-server: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.AMBIMAX_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.AMBIMAX_DOCKER_HUB_PASSWORD }}

      - name: Push image
        if: github.ref == 'refs/heads/v2'
        working-directory: 'dist/images/${{ matrix.WORKDIR }}'
        run: make push-image
        env:
          DOCKER_USER: ${{ secrets.AMBIMAX_DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.AMBIMAX_DOCKER_HUB_PASSWORD }}

  push-manifests:
    runs-on: ubuntu-latest
    needs: build-images
    if: github.ref == 'refs/heads/v2'
    strategy:
      matrix:
        WORKDIR:
          - 8.1/alpine3.22
          - 8.2/alpine3.23
          - 8.2/trixie
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare environment
        run: bash ${GITHUB_WORKSPACE}/.github/scripts/prepare-workflow.sh

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          # We push to the default registry currently. If you want to push to a different registry,
          # uncomment the line below.
          # login-server: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.AMBIMAX_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.AMBIMAX_DOCKER_HUB_PASSWORD }}

      - name: Create and push manifests
        working-directory: 'dist/images/${{ matrix.WORKDIR }}'
        run: make create-manifests
