name: Test Suite

on:
  push:
  schedule:
    # Update docker images at 04:25 on Mondays
    - cron: '25 4 * * 1'

jobs:
  dockerfile-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        WORKDIR:
          - 7.3/alpine3.13
          - 7.3/buster
          - 7.4/alpine3.13
          - 7.4/buster
          - 8.0/alpine3.13
          - 8.0/buster
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare environment
        run: bash ${GITHUB_WORKSPACE}/.github/scripts/prepare-workflow.sh

      - name: Build image
        working-directory: 'dist/images/${{ matrix.WORKDIR }}'
        run: make build

      - name: Test image
        working-directory: 'dist/images/${{ matrix.WORKDIR }}'
        run: make test

      - name: Additional image tests
        working-directory: 'dist/images/${{ matrix.WORKDIR }}'
        run: make official-test

      - name: Display all docker images
        if: ${{ always() }}
        run: docker images

      - name: Login to Docker Registry
        if: github.ref == 'refs/heads/v2'
        uses: docker/login-action@v1
        with:
          # We push to the default registry currently. If you want to push to a different registry,
          # uncomment the line below.
          # login-server: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REG_USERNAME }}
          password: ${{ secrets.DOCKER_REG_PASSWORD }}

      - name: Push image
        if: github.ref == 'refs/heads/v2'
        working-directory: 'dist/images/${{ matrix.WORKDIR }}'
        run: make push
        env:
          DOCKER_USER: ${{ secrets.DOCKER_REG_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_REG_PASSWORD }}
