on:
  push:
  schedule:
    # Update docker images at 04:25 on Mondays
    - cron: "25 4 * * 1"

jobs:
  dockerfile-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        WORKDIR:
          - 7.2/stretch/cli
          - 7.2/stretch/fpm
          - 7.3/buster/cli
          - 7.3/buster/fpm
          - 7.4/buster/cli
          - 7.4/buster/fpm
    defaults:
      run:
        working-directory: ${{ matrix.WORKDIR }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare environment
        run: bash ${GITHUB_WORKSPACE}/.github/scripts/prepare-workflow.sh

      - name: Build image
        run: make build

      - name: Test image
        run: make test

      - name: Additional image tests
        run: make official-test

      - name: Display all docker images
        if: ${{ always() }}
        run: docker images

      - name: Login to Docker Registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          # We push to the default registry currently. If you want to push to a different registry,
          # uncomment the line below.
          # login-server: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REG_USERNAME }}
          password: ${{ secrets.DOCKER_REG_PASSWORD }}

      - name: Push image
        if: github.ref == 'refs/heads/main'
        run: make push
        env:
          DOCKER_USER: ${{ secrets.DOCKER_REG_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_REG_PASSWORD }}
